version: "2"

services:
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
      - nexus
      # - freeipa
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.com
    ports:
      - "80:80"

  # NEXUS
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    build: 
      context: ./nexus
    ports:
      - "8081:8081"
    restart: unless-stopped

  # FREEIPA
  # freeipa:
  #   image: freeipa/freeipa-server:centos-8
  #   container_name: freeipa
  #   build: 
  #     context: ./freeipa
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "389:389"
  #     - "636:636"
  #     - "88:88"
  #     - "464:464"
  #     - "88:88/udp"
  #     - "464:464/udp"
  #     - "123:123/udp"
  #     - "7389:7389"
  #     - "9443:9443"
  #     - "9444:9444"
  #     - "9445:9445"
  #   restart: unless-stopped

  